### ISSUE TITLE
`npm run start`: failed to compile

### ISSUE THREAD

**Issue by Stefan-Hanke** [philihp/fields-of-arle#179]
![grafik](https://user-images.githubusercontent.com/1977938/49117072-e0339980-f29f-11e8-90f3-c4f894aa4e18.png)

Versions installed on my computer: NPM 6.4.0, Node 10.5.0, Win 7.

**Comment by Stefan-Hanke** [comment]
Oh never mind. The problem was the git `core.autocrlf` setting which was `true` at time of cloning.
Would you mind a PR adding a [.gitattributes fixing this](https://stackoverflow.com/questions/170961/whats-the-best-crlf-carriage-return-line-feed-handling-strategy-with-git)?

**Comment by philihp** [comment]
Oohhh sure of course! Thanks for reporting—I’d love to know if you find any other issues building on windows.

**Comment by Stefan-Hanke** [comment]
As a sidenote, Fields of Arle somehow managed to escape my attention. I've watched some rules explanation and bought it instantly, the fact that it is 1/2P fits perfectly :)

**Comment by philihp** [comment]
I know, right?! It's highly rated on BGG, but complicated enough that I doubt anyone else will make it online, aside from something like in Tabletop Simulator.

The only random element is in the setup, which offers a high degree of replayability. I actually cut a corner right now and only implemented a subset of the buildings. The way the destinations were coded, it would be relatively trivial to add the travel destination expansions (https://boardgamegeek.com/thread/1867794/new-travel-destinations-micro-expansions)
